# Site wide configuration

title: upday tech blog - now at medium
locale: en_US
description: Welcome! In our blog we share all the stuff that we - the tech dudettes & dudes of upday - struggled or had some fun with. Feel free to shoot us a message @UpdayDevs
logo: site-logo.svg
search: true
url: http://localhost:4000
# Jekyll configuration

excerpt_separator: <!-- more -->

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: upday dev
  avatar: bio-photo.jpg
  email: dev@upday.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:

social:
  twitter: UpdayDevs
  github: upday

inc:
  sharing:
    twitter: true
  google_font: 'Droid+Sans:400,700'
  cover: /images/cover.jpg